### ISSUE TITLE
Cannot install from melpa

### ISSUE THREAD

**Issue by PaulPichaureau** [hlissner/emacs-doom-theme#32] opened 2017-01-08 12:55 UTC
When I try to install the theme from package-lsit-package, it fails with the message:

package-compute-transaction: Package ‘font-lock+-0’ is unavailable

**Comment by hlissner** [comment] 2017-01-08 22:53
Looks like a duplicate of #28. I'll close this, please refer to that issue.

**Closed by hlissner** 2017-01-08 22:53 UTC
